### ISSUE TITLE
No CRAWL_ERRORS returned

### ISSUE THREAD

**Issue by stilliard** [eyecatchup/php-webmaster-tools-downloads#12]
I'm not getting any CRAWL_ERRORS csv's generated for my tests, can someone check if they are see'ing any.

_I do however see them in the crawl errors specific version:_ https://github.com/eyecatchup/GWT_CrawlErrors-php
_Though this uses the api's xml feed method instead of the csv, which atm doesn't seem to give the full results the csv would of._

**Comment by arpitHub** [comment]
Its because of some changes are done to Webmaster tools web interface.
Here is complete explanation :

http://stackoverflow.com/a/16002159
