### ISSUE TITLE
Feature of downloading full back links list

### ISSUE THREAD

**Issue by velPL** [eyecatchup/php-webmaster-tools-downloads#2]
Would you consider adding a feature to download full back links report which is on this page (https://www.google.com/webmasters/tools/external-links-domain?hl=pl&siteUrl= - download more sample links). I tried to add a feature to your script, but I believe security token is wrongly generated then.

**Comment by adduc** [comment]
I've added support for the latest backlinks report (very similar to full back links report), but I'd like to vet it more before submitting a pull request. I did have to make some changes to detect the proper security token in the page.

You can check out the change at https://github.com/Adduc/php-webmaster-tools-downloads

**Comment by robwent** [comment]
@adduc That's working well for me, pull pull!

Although it's the latest list it seems to go back to 2007 for the sites I've just tested so pretty good.

Thanks!

**Comment by eyecatchup** [comment]
merged PR #7
